import { mutation } from "./_generated/server";
import { v } from "convex/values";

const products = [
  {
    name: "Black Diamond Intense",
    slug: "black-diamond-intense",
    description: "An intense and captivating fragrance that embodies luxury and sophistication. With deep woody notes and a touch of musk, Black Diamond Intense is designed for those who command attention.",
    price: 21000,
    category: "Oriental",
    notes: ["Bergamot", "Black Pepper", "Leather", "Oud", "Amber", "Musk"],
    volume: "100ml",
    inStock: true,
    featured: true,
  },
  {
    name: "Emerald",
    slug: "emerald",
    description: "A fresh and vibrant fragrance inspired by the lush greenery of emerald forests. Green notes blend seamlessly with citrus and aquatic undertones.",
    price: 13000,
    category: "Fresh",
    notes: ["Green Apple", "Lemon", "Jasmine", "Moss", "Cedarwood", "Ambergris"],
    volume: "100ml",
    inStock: true,
    featured: true,
  },
  {
    name: "Brazilian Tobacco",
    slug: "brazilian-tobacco",
    description: "A bold and distinctive fragrance that captures the rich, warm essence of Brazilian tobacco leaves. Blended with honey and vanilla.",
    price: 9000,
    category: "Oriental",
    notes: ["Tobacco Leaf", "Honey", "Vanilla", "Cinnamon", "Leather", "Sandalwood"],
    volume: "100ml",
    inStock: true,
    featured: true,
  },
  {
    name: "Club de Nuits",
    slug: "club-de-nuits",
    description: "An enigmatic night-time fragrance designed for evening elegance and sophistication. With a blend of aromatic herbs and warm woods.",
    price: 10500,
    category: "Woody",
    notes: ["Grapefruit", "Lavender", "Sage", "Patchouli", "Vetiver", "Tonka Bean"],
    volume: "100ml",
    inStock: true,
    featured: true,
  },
  {
    name: "Royal Oud",
    slug: "royal-oud",
    description: "A regal fragrance centered around precious oud wood. Royal Oud combines the richness of agarwood with rose and saffron.",
    price: 18000,
    category: "Oriental",
    notes: ["Oud", "Rose", "Saffron", "Bergamot", "Cedar", "Amber"],
    volume: "75ml",
    inStock: true,
    featured: true,
  },
  {
    name: "Ocean Breeze",
    slug: "ocean-breeze",
    description: "A refreshing aquatic fragrance that transports you to a serene tropical coastline. Light, airy, and endlessly refreshing.",
    price: 9500,
    category: "Fresh",
    notes: ["Sea Salt", "Lemon", "Mint", "Lavender", "Cedar", "Musk"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Velvet Rose",
    slug: "velvet-rose",
    description: "A luxurious floral fragrance that celebrates the timeless beauty of the rose. Soft, velvety, and irresistibly elegant.",
    price: 11000,
    category: "Floral",
    notes: ["Rose", "Peach", "Violet", "Musk", "Vanilla", "Sandalwood"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Midnight Oud",
    slug: "midnight-oud",
    description: "A deeper, more mysterious take on classic oud. Dark woods, incense, and spice create an atmospheric evening scent.",
    price: 19500,
    category: "Oriental",
    notes: ["Oud", "Incense", "Black Pepper", "Leather", "Amber", "Patchouli"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Citrus Burst",
    slug: "citrus-burst",
    description: "An energetic explosion of citrus fruits that awakens the senses. Pure sunshine bottled.",
    price: 8500,
    category: "Fresh",
    notes: ["Lemon", "Orange", "Grapefruit", "Bergamot", "Ginger", "Mint"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Amber Nights",
    slug: "amber-nights",
    description: "A warm and sensual fragrance combining golden amber with vanilla and tonka bean. Cozy yet sophisticated.",
    price: 12000,
    category: "Oriental",
    notes: ["Amber", "Vanilla", "Tonka Bean", "Cinnamon", "Benzoin", "Musk"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Lavender Dreams",
    slug: "lavender-dreams",
    description: "A calming aromatic fragrance centered around the finest lavender. Serenity in a bottle.",
    price: 9000,
    category: "Aromatic",
    notes: ["Lavender", "Sage", "Rosemary", "Cedarwood", "Musk", "Coumarin"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Sandalwood Serenity",
    slug: "sandalwood-serenity",
    description: "A creamy, smooth sandalwood fragrance that embodies tranquility and balance.",
    price: 14000,
    category: "Woody",
    notes: ["Sandalwood", "Iris", "Cashmere Wood", "Vanilla", "Amber", "Musk"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Spiced Bergamot",
    slug: "spiced-bergamot",
    description: "A unique fusion of bright bergamot and warm spices creating an intriguing contrast.",
    price: 10000,
    category: "Fresh",
    notes: ["Bergamot", "Cinnamon", "Clove", "Nutmeg", "Ginger", "Cedar"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Musk Gold",
    slug: "musk-gold",
    description: "A luxurious interpretation of classic musk elevated with golden amber and precious woods.",
    price: 15000,
    category: "Oriental",
    notes: ["White Musk", "Amber", "Sandalwood", "Jasmine", "Rose", "Vanilla"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Green Tea & Mint",
    slug: "green-tea-mint",
    description: "A refreshing and invigorating fragrance inspired by the ritual of drinking green tea.",
    price: 8000,
    category: "Fresh",
    notes: ["Green Tea", "Mint", "Lemon", "Bergamot", "Jasmine", "Musk"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Dark Vanilla",
    slug: "dark-vanilla",
    description: "A sophisticated vanilla deepened with dark chocolate, coffee, and smoky woods. Rich and irresistible.",
    price: 11500,
    category: "Gourmand",
    notes: ["Madagascar Vanilla", "Dark Chocolate", "Coffee", "Cinnamon", "Sandalwood", "Musk"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Jasmine White",
    slug: "jasmine-white",
    description: "A pure and radiant floral showcasing night-blooming jasmine softened with white musk.",
    price: 10500,
    category: "Floral",
    notes: ["Jasmine", "White Musk", "Pear", "Lily of the Valley", "Sandalwood", "Amber"],
    volume: "75ml",
    inStock: true,
    featured: false,
  },
  {
    name: "Leather & Smoke",
    slug: "leather-smoke",
    description: "A bold, daring fragrance combining rugged leather with birch tar smoke and dark spices.",
    price: 16000,
    category: "Woody",
    notes: ["Leather", "Birch Tar", "Smoke", "Black Pepper", "Vetiver", "Amber"],
    volume: "100ml",
    inStock: true,
    featured: false,
  },
];

export const run = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if products already exist
    const existing = await ctx.db.query("products").first();
    if (existing) {
      return { status: "skipped", message: "Products already seeded" };
    }

    const now = Date.now();
    const imageIndexes: Record<string, number> = {
      "black-diamond-intense": 0,
      "emerald": 1,
      "brazilian-tobacco": 2,
      "club-de-nuits": 3,
      "royal-oud": 4,
      "ocean-breeze": 5,
      "velvet-rose": 6,
      "midnight-oud": 7,
      "citrus-burst": 8,
      "amber-nights": 9,
      "lavender-dreams": 10,
      "sandalwood-serenity": 11,
      "spiced-bergamot": 12,
      "musk-gold": 13,
      "green-tea-mint": 14,
      "dark-vanilla": 15,
      "jasmine-white": 16,
      "leather-smoke": 17,
    };

    for (const product of products) {
      await ctx.db.insert("products", {
        ...product,
        imageUrl: `/images/perfumes/WhatsApp Image 2026-07-26 at 09.46.${imageIndexes[product.slug] + 27}.jpeg`,
        createdAt: now,
      });
    }

    return { status: "success", seeded: products.length };
  },
});
